inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - db/schema.rb
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "**/*.builder"
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Max: 20
Naming/AccessorMethodName:
  Exclude:
    - app/controllers/bigbluebutton_api_controller.rb
Naming/MethodName:
  Exclude:
    - app/controllers/bigbluebutton_api_controller.rb
Rails:
  Enabled: true
Rails/CreateTableWithTimestamps:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
